title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          quotes:
            type: structure
            label: Structure field
            fields:
              test1:
                type: text
              test2:
                type: textarea
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

